server:
  port: 9120

spring:
  profiles:
    # 环境设置
    active: dev

  application:
    # 服务名
    name: service_oss

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.17:8848

  redis: # redis 配置
    host: 127.0.0.1
    port: 6379
    database: 0
    password:  #默认为空
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    KeyId: LTAIbUa1VjmLtLj9
    keySecret: 0DwE37E2aVQ17K0xrWJtJMmjM54ZeM
    bucketName: javaclimb-file
